{
 "title": "IDTC-NOC-BD-001 - SQL Reportes T24",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uso de CPU BD PROD T24",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(windows_cpu_time_total{job=~\"BD\", instance=\"10.138.7.231\", mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "{{instancia}}"
    }
   ]
  },
  {
   "title": "Uso de CPU BD ANALYTICS T24",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(windows_cpu_time_total{job=~\"BD\", instance=\"10.138.7.171\", mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "{{instancia}}"
    }
   ]
  },
  {
   "title": "ESTADO BD PROD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"SERVICIOS-APPL-BD-PING\", instance=\"10.138.7.231\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USO DE RAM BD PROD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_memory_committed_bytes{job=\"BD\", instance=\"10.138.7.231\"} / \r\n (windows_memory_committed_bytes{job=\"BD\", instance=\"10.138.7.231\"} + \r\n  windows_memory_available_bytes{job=\"BD\", instance=\"10.138.7.231\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESTADO BD ANALYTICS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"SERVICIOS-APPL-BD-PING\", instance=\"10.138.7.171\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USO DE RAM BD ANALYTICS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_memory_committed_bytes{job=\"BD\", instance=\"10.138.7.171\"} / \r\n (windows_memory_committed_bytes{job=\"BD\", instance=\"10.138.7.171\"} + \r\n  windows_memory_available_bytes{job=\"BD\", instance=\"10.138.7.171\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Espacio restante de los discos BD PROD",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  windows_logical_disk_free_bytes{instance=\"10.138.7.231\", volume!~\"HarddiskVolume.+|\\\\\\\\\\\\\\\\\\\\?\\\\\\\\\\\\\\\\Volume.+\"} \r\n  / \r\n  windows_logical_disk_size_bytes{instance=~\"10.138.7.231\", volume!~\"HarddiskVolume.+|\\\\\\\\\\\\\\\\\\\\?\\\\\\\\\\\\\\\\Volume.+\"} \r\n  * 100\r\n)",
     "legendFormat": "{{instance}}-{{volume}}"
    }
   ]
  },
  {
   "title": "Espacio restante de los discos BD PROD",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  windows_logical_disk_free_bytes{instance=\"10.138.7.171\", volume!~\"HarddiskVolume.+|\\\\\\\\\\\\\\\\\\\\?\\\\\\\\\\\\\\\\Volume.+\"} \r\n  / \r\n  windows_logical_disk_size_bytes{instance=~\"10.138.7.171\", volume!~\"HarddiskVolume.+|\\\\\\\\\\\\\\\\\\\\?\\\\\\\\\\\\\\\\Volume.+\"} \r\n  * 100\r\n)",
     "legendFormat": "{{instance}}-{{volume}}"
    }
   ]
  }
 ]
}