{
 "title": "Monitoreo Transferencias",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Cooperativa",
    "query": "SELECT [cooperativa]\nFROM [TokenMiCoope].[dbo].[Token_Cooperativa]"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"\n    font-size: 3rem;\n    font-weight: 700;\n    font-family: 'Century';\n    color: #49BF22;\n    padding-bottom: 7px;\n    -- border-bottom: 0.5px solid #FFFFFF;\n    text-align: center;\n\">\n    Monitoreo Micoope en Línea\n</h1>\n"
   }
  },
  {
   "title": "Cantidad de Tokens Generados por Día",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "DECLARE @FROM datetime = $__timeFrom();\r\nDECLARE @TO   datetime = $__timeTo();\r\n\r\nWITH Transacciones AS (\r\n    SELECT\r\n        TK.username AS Usuario,\r\n        TR.description_transac AS Tipo,\r\n        COUNT(DISTINCT TK.token) AS Cantidad\r\n    FROM [TokenMiCoope].[dbo].[Token_LogGeneration] TK\r\n\r\n    LEFT JOIN [TokenMiCoope].[dbo].[Token_Transaction_C1] TR\r\n        ON TK.transaction_id = TR.id\r\n\r\n    WHERE TK.created_at BETWEEN @FROM AND @TO\r\n      --AND TK.username = 'JGMARIA'\r\n\r\n    GROUP BY\r\n        TK.username,\r\n        TR.description_transac\r\n),\r\n\r\nUsuarioInfo AS (\r\n    SELECT\r\n        username,\r\n        MAX(phone) AS Telefono,\r\n        MAX(mail) AS Correo\r\n    FROM [TokenMiCoope].[dbo].[Token_Users]\r\n    GROUP BY username\r\n),\r\n\r\nCoopsDistinct AS (\r\n    SELECT DISTINCT\r\n        us.username,\r\n        cope.cooperativa\r\n    FROM [TokenMiCoope].[dbo].[Token_Users_Extension] us\r\n\r\n    INNER JOIN [TokenMiCoope].[dbo].[Token_Cooperativa] cope\r\n        ON cope.id = us.id_cooperativa\r\n\r\n    WHERE cope.cooperativa <> 'Guadalupana'\r\n),\r\n\r\nCoops AS (\r\n    SELECT\r\n        username,\r\n        STRING_AGG(cooperativa, ' | ') AS Cooperativa\r\n    FROM CoopsDistinct\r\n    GROUP BY username\r\n)\r\n\r\nSELECT\r\n    C.Cooperativa,\r\n    T.Usuario,\r\n    U.Telefono,\r\n    U.Correo,\r\n    SUM(T.Cantidad) AS Total,\r\n    STRING_AGG(\r\n        CONCAT(T.Tipo, ': ', T.Cantidad),\r\n        '  |  '\r\n    ) AS Detalle\r\nFROM Transacciones T\r\n\r\nLEFT JOIN UsuarioInfo U\r\n    ON T.Usuario = U.username\r\n\r\nINNER JOIN Coops C\r\n    ON T.Usuario = C.username\r\n\r\nGROUP BY\r\n    C.Cooperativa,\r\n    T.Usuario,\r\n    U.Telefono,\r\n    U.Correo\r\n\r\nORDER BY\r\n    Total DESC;"
    }
   ]
  },
  {
   "title": "Cantidad de Tokens Ingresados en Micoope en Línea",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "/***** CANTIDAD DE TOKENS INGRESADOS EN MICOOPE EN LINEA por USUARIO Y FECHA *****/\r\nDECLARE @FROM datetime = $__timeFrom();\r\nDECLARE @TO   datetime = $__timeTo();\r\n\r\nSELECT \r\n\tcope.cooperativa AS Cooperativa,\r\n\ttk.username AS Usuario,\r\n\tCOUNT (tk.token) AS [Cantidad]\r\nFROM [TokenMiCoope].[dbo].[Token_LogValidation] tk\r\nLEFT JOIN [TokenMiCoope].[dbo].[Token_Users_Extension] us ON tk.username = us.username\r\nLEFT JOIN [TokenMiCoope].[dbo].[Token_Cooperativa] cope ON cope.id = us.id_cooperativa\r\nWHERE [created_at] BETWEEN @FROM AND @TO \r\nGROUP BY cope.cooperativa, tk.username\r\nHAVING COUNT(*) >= 5\r\nORDER BY Cantidad DESC"
    }
   ]
  },
  {
   "title": "Cantidad de Tokens Generados por Día",
   "type": "table",
   "description": "Con Filtro",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 15 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "/****** CANTIDAD DE TOKENS GENERADOS POR DÍA ******/\r\n\r\nDECLARE @FROM datetime = $__timeFrom();\r\nDECLARE @TO   datetime = $__timeTo();\r\n\r\nWITH UsuarioReciente AS (\r\n    SELECT\r\n        usr.username,\r\n        usr.phone,\r\n        usr.mail,\r\n        usr.created_at,\r\n        ROW_NUMBER() OVER (\r\n            PARTITION BY usr.username\r\n            ORDER BY usr.created_at DESC\r\n        ) AS rn\r\n    FROM [TokenMiCoope].[dbo].[Token_Users] usr\r\n),\r\n\r\nExtensionUnica AS (\r\n    SELECT DISTINCT\r\n        username,\r\n        id_cooperativa\r\n    FROM [TokenMiCoope].[dbo].[Token_Users_Extension]\r\n),\r\n\r\nDatos AS (\r\n    SELECT\r\n        cope.cooperativa AS Cooperativa,\r\n        tk.username AS Usuario,\r\n        tr.description_transac AS Tipo,\r\n        COUNT(DISTINCT tk.token) AS Cantidad,\r\n        MAX(usr.phone) AS Telefono,\r\n        MAX(usr.mail) AS Correo\r\n    FROM [TokenMiCoope].[dbo].[Token_LogGeneration] tk\r\n\r\n    LEFT JOIN [TokenMiCoope].[dbo].[Token_Transaction_C1] tr\r\n        ON tk.transaction_id = tr.id\r\n\r\n    LEFT JOIN ExtensionUnica us\r\n        ON tk.username = us.username\r\n\r\n    LEFT JOIN [TokenMiCoope].[dbo].[Token_Cooperativa] cope\r\n        ON cope.id = us.id_cooperativa\r\n\r\n    LEFT JOIN UsuarioReciente usr\r\n        ON usr.username = tk.username\r\n       AND usr.rn = 1\r\n\r\n    WHERE tk.[created_at] BETWEEN @FROM AND @TO\r\n      AND cope.cooperativa <> 'Guadalupana'\r\n      AND (\r\n            '${Cooperativa}' = 'All'\r\n\t\t\tOR cope.cooperativa IN (${Cooperativa:sqlstring})\r\n            --OR cope.cooperativa IN (@COPE)\r\n      )\r\n\r\n    GROUP BY\r\n        cope.cooperativa,\r\n        tk.username,\r\n        tr.description_transac\r\n)\r\n\r\nSELECT TOP 100\r\n    Cooperativa,\r\n    Usuario,\r\n    MAX(Telefono) AS Telefono,\r\n    MAX(Correo) AS Correo,\r\n    SUM(Cantidad) AS Cantidad,\r\n    STRING_AGG(\r\n        CONCAT(ISNULL(Tipo, 'Sin tipo'), ': ', Cantidad),\r\n        '  |  '\r\n    ) AS Detalle\r\nFROM Datos\r\nGROUP BY\r\n    Cooperativa,\r\n    Usuario\r\nHAVING SUM(Cantidad) >= 5\r\nORDER BY\r\n    Cantidad DESC,\r\n    Usuario;"
    }
   ]
  },
  {
   "title": "Transacciones ACH ",
   "type": "table",
   "description": "Verifica la cantidad de transacciones que recibe una misma cuenta ACH\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "DECLARE @FROM VARCHAR(10);\r\nDECLARE @TO VARCHAR(10);\r\n\r\nSET @FROM = FORMAT(TRY_CONVERT(DATETIME, $__timeFrom()), 'yyMMddHHmm');\r\n\r\nSET @TO = FORMAT(TRY_CONVERT(DATETIME, $__timeTo()), 'yyMMddHHmm');\r\n\r\n\r\n\r\nSELECT \r\n    COUNT(*) AS TOTAL_TRANSACCIONES,\r\n    NOM_CUENTA_DESTINO,\r\n    NOMBRE_BANK,\r\n    MIN(MONTOS) MINIMO,\r\n    MAX(MONTOS) MAXIMO,\r\n    SUM(MONTOS) TOTAL\r\nFROM (\r\n    SELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST(MONTO AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA02_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK)\r\n    WHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\r\n    UNION ALL\r\n\r\n    SELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST(MONTO AS DECIMAL(18,2))\r\n    FROM [FENANC].[dbo].[V_FA04_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK)\r\n    WHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n \tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST(MONTO AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA05_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST(MONTO AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA06_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST(MONTO AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA07_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n    SELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST(MONTO AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA08_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n    SELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA09_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA11_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA12_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA13_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA14_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA15_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA16_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA17_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA18_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA19_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA20_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA21_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\t\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA22_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA23_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA24_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA25_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA26_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA27_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA50_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA51_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA52_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA55_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA56_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n\tUNION ALL\r\n\r\n\tSELECT CUENTA_DESTINO, NOM_CUENTA_DESTINO, NOMBRE_BANK, CAST( MONTO  AS DECIMAL(18,2)) AS MONTOS\r\n    FROM [FENANC].[dbo].[V_FA57_EB_GT01_ACH_EFECTUADA_SALIENTE] WITH (NOLOCK) \r\n\tWHERE DATE_TIME BETWEEN @FROM AND @TO\r\n\t\r\n    \r\n) T\r\nGROUP BY \r\n    NOM_CUENTA_DESTINO,\r\n    NOMBRE_BANK\r\nHAVING COUNT(*) >= 2\r\nORDER BY TOTAL_TRANSACCIONES DESC\r\nOPTION (MAXDOP 1);"
    }
   ]
  }
 ]
}