{
 "title": "Querys DB - SRV 10.138.7.71 - Monitor Plus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Servidor BD 71</h1></center>\r\n"
   }
  },
  {
   "title": "Sesiones Activas SRV_BD_231",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "AnalyticsImport",
     "rawSql": "IF EXISTS(\r\n    SELECT 1\r\n    FROM sys.dm_tran_active_snapshot_database_transactions AS ast\r\n    JOIN sys.dm_tran_active_transactions AS at ON at.transaction_id = ast.transaction_id\r\n    JOIN sys.dm_exec_sessions AS ses ON ses.session_id = ast.session_id\r\n    JOIN sys.dm_exec_connections AS con ON con.session_id = ses.session_id\r\n)\r\nBEGIN\r\n    SELECT TOP 10 \r\n        ses.session_id AS [Session ID],\r\n        DB_NAME(database_id) AS [Database Name],\r\n        CASE at.transaction_state\r\n            WHEN 0 THEN 'init'\r\n            WHEN 1 THEN 'init'\r\n            WHEN 2 THEN 'active'\r\n            WHEN 3 THEN 'ended'\r\n            WHEN 4 THEN 'committing'\r\n            WHEN 6 THEN 'committed'\r\n            WHEN 7 THEN 'rolling back'\r\n            ELSE 'other'\r\n        END AS [Transaction State],\r\n        at.transaction_begin_time AS [Transaction Start Time],\r\n        ast.elapsed_time_seconds AS [Elapsed Time],\r\n        CASE \r\n            WHEN at.transaction_type = 1 THEN 'Read/Write'\r\n            WHEN at.transaction_type = 2 THEN 'Read-Only'\r\n            ELSE 'System'\r\n        END AS [Transaction Type],\r\n        ses.login_name AS [Login],\r\n        ses.program_name AS [Origin Program],\r\n        con.client_net_address AS [Client IP],\r\n        ses.host_name AS [Host Name]\r\n    FROM sys.dm_tran_active_snapshot_database_transactions AS ast\r\n    JOIN sys.dm_tran_active_transactions AS at ON at.transaction_id = ast.transaction_id\r\n    JOIN sys.dm_exec_sessions AS ses ON ses.session_id = ast.session_id\r\n    JOIN sys.dm_exec_connections AS con ON con.session_id = ses.session_id\r\n WHERE ast.elapsed_time_seconds > 5\r\n    ORDER BY at.transaction_begin_time \r\nEND\r\nELSE\r\nBEGIN \r\n    SELECT \r\n        '' AS [Session ID],\r\n        '' AS [Database Name],\r\n        '' AS [Transaction State],\r\n        '' AS [Transaction Start Time],\r\n        '' AS [Elapsed Time],\r\n        '' AS [Transaction Type],\r\n        '' AS [Login],\r\n        '' AS [Origin Program],\r\n        '' AS [Client IP],\r\n        '' AS [Host Name]\r\nEND\r\n "
    }
   ]
  },
  {
   "title": "Consultas mas frecuentes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "FENANC",
     "rawSql": "WITH CPU_Stats AS (\r\n    SELECT  \r\n        total_worker_time / execution_count AS AvgCPU,\r\n        execution_count,\r\n        total_worker_time AS TotalCPU,\r\n        text AS Consulta\r\n    FROM sys.dm_exec_query_stats \r\n    CROSS APPLY sys.dm_exec_sql_text(sql_handle)\r\n)\r\nSELECT TOP 5\r\n    Consulta,\r\n    (TotalCPU * 100.0 / SUM(TotalCPU) OVER()) AS 'Porcentaje CPU'\r\nFROM CPU_Stats\r\nORDER BY 'Porcentaje CPU' DESC;\r\n"
    }
   ]
  },
  {
   "title": "BloqueosBD",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "AnalyticsImport",
     "rawSql": "IF EXISTS(\r\n    SELECT 1\r\n    FROM \r\n    sys.dm_tran_locks bl\r\n\tJOIN \r\n\t\tsys.dm_os_waiting_tasks wt ON bl.lock_owner_address = wt.resource_address\r\n\tJOIN \r\n\t\tsys.dm_exec_requests req ON bl.request_session_id = req.session_id\r\n\tCROSS APPLY \r\n\t\tsys.dm_exec_sql_text(req.sql_handle) AS txt\r\n\r\n)\r\nBEGIN\r\n    SELECT\r\n\t\tbl.request_session_id AS Sesion_Bloqueada,\r\n\t\twt.blocking_session_id AS Sesion_Bloqueadora,\r\n\t\tDB_NAME(req.database_id) AS Base_De_Datos,\r\n\t\treq.wait_time / 1000.0 AS Tiempo_Espera_Seg,\r\n\t\tLEFT(txt.text, 200) AS Consulta_Bloqueada -- solo primeros 200 caracteres\r\n\tFROM \r\n\t\tsys.dm_tran_locks bl\r\n\tJOIN \r\n\t\tsys.dm_os_waiting_tasks wt ON bl.lock_owner_address = wt.resource_address\r\n\tJOIN \r\n\t\tsys.dm_exec_requests req ON bl.request_session_id = req.session_id\r\n\tCROSS APPLY \r\n\t\tsys.dm_exec_sql_text(req.sql_handle) AS txt\r\n\tORDER BY \r\n\t\tTiempo_Espera_Seg DESC\r\nEND\r\nELSE\r\nBEGIN \r\n    SELECT \r\n        '' as Sesion_Bloqueada,\r\n\t\t'' as Sesion_Bloqueadora,\r\n\t\t'' as Base_De_Datos,\r\n\t\t'' as Tiempo_Espera_Seg,\r\n\t\t'' as Consulta_Bloqueada\r\nEND\r\n\r\n"
    }
   ]
  }
 ]
}