{
 "title": "Querys DB - SRV 10.138.7.171 - ANALYTICS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"\r\n    font-size: 3rem;\r\n    font-weight: 700;\r\n    font-family: 'Century';\r\n    color: #49BF22;\r\n    padding-bottom: 8px;\r\n    -- border-bottom: 0.5px solid #FFFFFF;\r\n    text-align: center;\r\n\">\r\n    Servidor Base de Datos 171\r\n</h1>"
   }
  },
  {
   "title": "Sesiones Activas SRV_BD_171",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "AnalyticsImport",
     "rawSql": "IF EXISTS(\r\n    SELECT 1\r\n    FROM sys.dm_tran_active_snapshot_database_transactions AS ast\r\n    JOIN sys.dm_tran_active_transactions AS at ON at.transaction_id = ast.transaction_id\r\n    JOIN sys.dm_exec_sessions AS ses ON ses.session_id = ast.session_id\r\n    JOIN sys.dm_exec_connections AS con ON con.session_id = ses.session_id\r\n)\r\nBEGIN\r\n    SELECT TOP 10 \r\n        ses.session_id AS [Session ID],\r\n        DB_NAME(database_id) AS [Database Name],\r\n        CASE at.transaction_state\r\n            WHEN 0 THEN 'init'\r\n            WHEN 1 THEN 'init'\r\n            WHEN 2 THEN 'active'\r\n            WHEN 3 THEN 'ended'\r\n            WHEN 4 THEN 'committing'\r\n            WHEN 6 THEN 'committed'\r\n            WHEN 7 THEN 'rolling back'\r\n            ELSE 'other'\r\n        END AS [Transaction State],\r\n        at.transaction_begin_time AS [Transaction Start Time],\r\n        ast.elapsed_time_seconds AS [Elapsed Time],\r\n        CASE \r\n            WHEN at.transaction_type = 1 THEN 'Read/Write'\r\n            WHEN at.transaction_type = 2 THEN 'Read-Only'\r\n            ELSE 'System'\r\n        END AS [Transaction Type],\r\n        ses.login_name AS [Login],\r\n        ses.program_name AS [Origin Program],\r\n        con.client_net_address AS [Client IP],\r\n        ses.host_name AS [Host Name]\r\n    FROM sys.dm_tran_active_snapshot_database_transactions AS ast\r\n    JOIN sys.dm_tran_active_transactions AS at ON at.transaction_id = ast.transaction_id\r\n    JOIN sys.dm_exec_sessions AS ses ON ses.session_id = ast.session_id\r\n    JOIN sys.dm_exec_connections AS con ON con.session_id = ses.session_id\r\n WHERE ast.elapsed_time_seconds > 5\r\n    ORDER BY at.transaction_begin_time \r\nEND\r\nELSE\r\nBEGIN \r\n    SELECT \r\n        '' AS [Session ID],\r\n        '' AS [Database Name],\r\n        '' AS [Transaction State],\r\n        '' AS [Transaction Start Time],\r\n        '' AS [Elapsed Time],\r\n        '' AS [Transaction Type],\r\n        '' AS [Login],\r\n        '' AS [Origin Program],\r\n        '' AS [Client IP],\r\n        '' AS [Host Name]\r\nEND\r\n "
    }
   ]
  },
  {
   "title": "BloqueosBD",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "AnalyticsImport",
     "rawSql": "IF EXISTS (SELECT 1 FROM sys.dm_exec_requests WHERE blocking_session_id <> 0)\r\nBEGIN\r\n    SELECT \r\n        -- 1. INFORMACIÓN DE LA SESIÓN BLOQUEADA (La víctima)\r\n        r.session_id AS 'Sesion Bloqueada',\r\n        s_blocked.login_name AS 'Usuario Bloqueado',\r\n        s_blocked.host_name AS 'Servidor Bloqueado',\r\n        s_blocked.program_name AS 'App Bloqueada',\r\n        DB_NAME(r.database_id) AS 'Base de Datos',\r\n        CAST(r.wait_time / 1000.0 AS DECIMAL(10,2)) AS 'Segundos Activa',\r\n        r.wait_type AS 'Tipo de Espera',\r\n        LEFT(t_blocked.text, 200) AS 'Consulta Bloqueada',\r\n\r\n        -- 2. INFORMACIÓN DE LA SESIÓN BLOQUEADORA (El responsable)\r\n        r.blocking_session_id AS 'Sesion Bloqueadora',\r\n        s_blocker.login_name AS 'Usuario Bloqueador',\r\n        s_blocker.host_name AS 'Servidor Bloqueador',\r\n        s_blocker.program_name AS 'App Bloqueadora',\r\n        s_blocker.status AS 'Estado Bloqueador',\r\n        LEFT(t_blocker.text, 200) AS 'Ultima Consulta Bloqueador'\r\n\r\n    FROM sys.dm_exec_requests r\r\n    -- Unimos con sesiones para obtener datos de la VÍCTIMA\r\n    INNER JOIN sys.dm_exec_sessions s_blocked \r\n        ON r.session_id = s_blocked.session_id\r\n    OUTER APPLY sys.dm_exec_sql_text(r.sql_handle) t_blocked\r\n    \r\n    -- Unimos con sesiones para obtener datos del RESPONSABLE\r\n    LEFT JOIN sys.dm_exec_sessions s_blocker \r\n        ON r.blocking_session_id = s_blocker.session_id\r\n    -- Unimos con conexiones para saber qué fue lo último que ejecutó el bloqueador\r\n    LEFT JOIN sys.dm_exec_connections c_blocker \r\n        ON s_blocker.session_id = c_blocker.session_id\r\n    OUTER APPLY sys.dm_exec_sql_text(c_blocker.most_recent_sql_handle) t_blocker\r\n\r\n    WHERE r.blocking_session_id <> 0\r\n    ORDER BY r.wait_time DESC;\r\nEND\r\nELSE\r\nBEGIN \r\n    -- Se devuelven las mismas columnas vacías si no hay bloqueos\r\n    SELECT \r\n        '' AS 'Sesion Bloqueada',\r\n        '' AS 'Usuario Bloqueado',\r\n        '' AS 'Servidor Bloqueado',\r\n        '' AS 'App Bloqueada',\r\n        '' AS 'Base de Datos',\r\n        '' AS 'Segundos Activa',\r\n        '' AS 'Tipo de Espera',\r\n        '' AS 'Consulta Bloqueada',\r\n        '' AS 'Sesion Bloqueadora',\r\n        '' AS 'Usuario Bloqueador',\r\n        '' AS 'Servidor Bloqueador',\r\n        '' AS 'App Bloqueadora',\r\n        '' AS 'Estado Bloqueador',\r\n        '' AS 'Ultima Consulta Bloqueador';\r\nEND"
    }
   ]
  },
  {
   "title": "Bloqueos",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "SELECT \r\n    GETDATE() AS time,\r\n    COUNT(*) AS bloqueos\r\nFROM sys.dm_exec_requests r\r\nINNER JOIN sys.dm_exec_sessions s_blocked \r\n    ON r.session_id = s_blocked.session_id\r\nLEFT JOIN sys.dm_exec_sessions s_blocker \r\n    ON r.blocking_session_id = s_blocker.session_id\r\nLEFT JOIN sys.dm_exec_connections c_blocker \r\n    ON s_blocker.session_id = c_blocker.session_id\r\nWHERE r.blocking_session_id <> 0;"
    }
   ]
  },
  {
   "title": "Consultas mas frecuentes",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "dataset": "FENANC",
     "rawSql": "WITH CPU_Stats AS (\r\n    SELECT  \r\n        total_worker_time / execution_count AS AvgCPU,\r\n        execution_count,\r\n        total_worker_time AS TotalCPU,\r\n        text AS Consulta\r\n    FROM sys.dm_exec_query_stats \r\n    CROSS APPLY sys.dm_exec_sql_text(sql_handle)\r\n)\r\nSELECT TOP 5\r\n    Consulta,\r\n    (TotalCPU * 100.0 / SUM(TotalCPU) OVER()) AS 'Porcentaje CPU'\r\nFROM CPU_Stats\r\nORDER BY 'Porcentaje CPU' DESC;\r\n"
    }
   ]
  }
 ]
}