{
 "title": "Querys DB - SRV 10.138.2.198 - CANALES",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"\r\n    font-size: 3rem;\r\n    font-weight: 700;\r\n    font-family: 'Century';\r\n    color: #49BF22;\r\n    padding-bottom: 7px;\r\n    -- border-bottom: 0.5px solid #FFFFFF;\r\n    text-align: center;\r\n\">\r\n    Servidor Base de Datos 2.198\r\n</h1>\r\n"
   }
  },
  {
   "title": "Sesiones Activas ",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "AnalyticsImport",
     "rawSql": "IF EXISTS(\r\n    SELECT 1\r\n    FROM sys.dm_tran_active_snapshot_database_transactions AS ast\r\n    JOIN sys.dm_tran_active_transactions AS at ON at.transaction_id = ast.transaction_id\r\n    JOIN sys.dm_exec_sessions AS ses ON ses.session_id = ast.session_id\r\n    JOIN sys.dm_exec_connections AS con ON con.session_id = ses.session_id\r\n)\r\nBEGIN\r\n    SELECT TOP 10 \r\n        ses.session_id AS [SesionID],\r\n        DB_NAME(ses.database_id) AS [Base de Datos],\r\n        ses.login_name AS [Usuario],\r\n        ses.program_name AS [Programa de Origen],\r\n        ses.status AS [Estatus],\r\n\t\tFORMAT(at.transaction_begin_time, 'dd/MM/yy  -  HH:mm:ss') AS [Inicio],\r\n        CASE \r\n\t\t\tWHEN DATEDIFF(SECOND, at.transaction_begin_time, GETDATE()) < 60 THEN 1\r\n\t\t\tELSE DATEDIFF(MINUTE, at.transaction_begin_time, GETDATE()) \r\n\t\tEND AS [Minutos Activa],\r\n        con.client_net_address AS [IP del Cliente],\r\n        ses.host_name AS [Host],\r\n        ISNULL(t.text, '-') AS [Consulta SQL]\r\n    FROM sys.dm_tran_active_snapshot_database_transactions AS ast\r\n    JOIN sys.dm_tran_active_transactions AS at ON at.transaction_id = ast.transaction_id\r\n    JOIN sys.dm_exec_sessions AS ses ON ses.session_id = ast.session_id\r\n    JOIN sys.dm_exec_connections AS con ON con.session_id = ses.session_id\r\n    LEFT JOIN sys.dm_exec_requests r ON ses.session_id = r.session_id\r\n    OUTER APPLY sys.dm_exec_sql_text(r.sql_handle) AS t\r\n    WHERE ast.elapsed_time_seconds > 5\r\n    ORDER BY at.transaction_begin_time \r\nEND\r\nELSE\r\nBEGIN \r\n    SELECT \r\n        '' AS [SesionID],\r\n        '' AS [Base de Datos],\r\n        '' AS [Usuario],\r\n        '' AS [Programa de Origen],\r\n        '' AS [Estatus],\r\n        '' AS [Inicio],\r\n        '' AS [Minutos Activa],\r\n        '' AS [IP del Cliente],\r\n        '' AS [Host],\r\n        '' AS [Consulta SQL]\r\nEND\r\n"
    }
   ]
  },
  {
   "title": "Tablas con mayor tamaño SoyFriDB",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "USE SoyFriDB;\r\n\r\nSELECT TOP 5\r\n    t.NAME AS Tabla,\r\n    s.Name AS Esquema,\r\n    CAST(ROUND((SUM(a.total_pages) * 8) / 1024.00, 2) AS DECIMAL(10,2)) AS TamañoMB,\r\n    CAST(ROUND((SUM(a.used_pages) * 8) / 1024.00, 2) AS DECIMAL(10,2)) AS EspacioUsadoMB,\r\n    CAST(ROUND((SUM(a.data_pages) * 8) / 1024.00, 2) AS DECIMAL(10,2)) AS DatosMB\r\nFROM \r\n    sys.tables t\r\nINNER JOIN      \r\n    sys.indexes i ON t.object_id = i.object_id\r\nINNER JOIN \r\n    sys.partitions p ON i.object_id = p.object_id AND i.index_id = p.index_id\r\nINNER JOIN \r\n    sys.allocation_units a ON p.partition_id = a.container_id\r\nLEFT OUTER JOIN \r\n    sys.schemas s ON t.schema_id = s.schema_id\r\nWHERE \r\n    t.is_ms_shipped = 0\r\nGROUP BY \r\n    t.Name, s.Name, p.Rows\r\nORDER BY \r\n    TamañoMB DESC;"
    }
   ]
  },
  {
   "title": "Bloqueos en BD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "SELECT \r\n    GETDATE() AS time,\r\n    COUNT(*) AS bloqueos\r\nFROM sys.dm_exec_requests r\r\nINNER JOIN sys.dm_exec_sessions s_blocked \r\n    ON r.session_id = s_blocked.session_id\r\nLEFT JOIN sys.dm_exec_sessions s_blocker \r\n    ON r.blocking_session_id = s_blocker.session_id\r\nLEFT JOIN sys.dm_exec_connections c_blocker \r\n    ON s_blocker.session_id = c_blocker.session_id\r\nWHERE r.blocking_session_id <> 0;"
    }
   ]
  }
 ]
}