{
 "title": "IDTC-NOC-BD-001 - SQL producción T24",
 "description": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(windows_os_hostname{job=\"BD\"},job)"
    }
   },
   {
    "name": "instancia",
    "label": "instancia",
    "query": {
     "query": "label_values(windows_os_hostname{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(windows_os_hostname{instance=~\"$instancia\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uso de CPU BD PROD T24",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(windows_cpu_time_total{job=~\"BD\", instance=\"10.138.7.231\", mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "{{instancia}}"
    }
   ]
  },
  {
   "title": "Uso de CPU por job $job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(windows_cpu_time_total{job=~\"BD\", mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "{{instancia}}"
    }
   ]
  },
  {
   "title": "Estado $instancia",
   "type": "stat",
   "description": "PING HACIA SRV\n1 = arriba\n2 = down",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"SERVICIOS-APPL-BD-PING\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Espacio restante del disco SRV $instancia",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  windows_logical_disk_free_bytes{job=\"BD\", volume!~\"HarddiskVolume.+|\\\\\\\\\\\\\\\\\\\\?\\\\\\\\\\\\\\\\Volume.+\"} \r\n  / \r\n  windows_logical_disk_size_bytes{job=\"BD\", instance=~\"$instancia\", volume!~\"HarddiskVolume.+|\\\\\\\\\\\\\\\\\\\\?\\\\\\\\\\\\\\\\Volume.+\"} \r\n  * 100\r\n)",
     "legendFormat": "{{instance}}-{{volume}}"
    }
   ]
  },
  {
   "title": "Detalles de la tarjeta de red de mayor tráfico",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\", instance=~\"$instancia\", nic!~'isatap.*|VPN.*'}[2m]))*8",
     "legendFormat": "{{instance}}_Subida"
    },
    {
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\", instance=~\"$instancia\", nic!~'isatap.*|VPN.*'}[2m]))*8",
     "legendFormat": "{{instance}}_Descarga"
    }
   ]
  },
  { "title": "Alertas", "type": "alertlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 8 } },
  {
   "title": "USO RAM $instancia",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_memory_committed_bytes{job=\"BD\", instance=~\"$instancia\"} / \r\n (windows_memory_committed_bytes{job=\"BD\", instance=~\"$instancia\"} + \r\n  windows_memory_available_bytes{job=\"BD\", instance=~\"$instancia\"})) * 100\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Detalles de IO de disco de mayor tráfico",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "-max by(instance) (irate(windows_logical_disk_reads_total{job=~\"$job\", instance=~\"$instancia\"}[2m]))",
     "legendFormat": "{{instance}}_Lectura"
    },
    {
     "expr": "max by(instance) (irate(windows_logical_disk_writes_total{job=~\"$job\", instance=~\"$instancia\"}[2m]))",
     "legendFormat": "{{instance}}_Escritura"
    }
   ]
  },
  {
   "title": "Detalles de lectura/escritura de disco de mayor tráfico",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-max by(instance) (irate(windows_logical_disk_reads_total{job=~\"$job\", instance=~\"$instancia\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance) (irate(windows_logical_disk_writes_total{job=~\"$job\", instance=~\"$instancia\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}