{
 "title": "Cooperativa Encarnación - AGENTES",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(probe_success{instance=~\"R1_SRV_AGENTES1_Nodo1|R1_SRV_AGENTES1_Nodo2|R1_SRV_AGENTES2_Nodo1|R1_SRV_AGENTES2_Nodo2\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(windows_os_hostname{job=~\"SRVS_AGENTES\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 13, "x": 5, "y": 0 },
   "options": {
    "content": "<img src=\"https://i.postimg.cc/85dxZwjY/Dashboard-especial.png\" alt=\"NOC Fondo\">\n"
   }
  },
  {
   "title": "Uso de CPU ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by(instance) (\r\n    irate(windows_cpu_time_total{\r\n      job=\"AGENTES\",\r\n      instance=~\"10.138.3.121|10.138.3.122\",\r\n      mode=\"idle\"\r\n    }[30s])\r\n  ) * 100\r\n)",
     "legendFormat": "Servidores_024Encarnacion"
    }
   ]
  },
  {
   "title": "Uso de memoria RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg by(instance) (\r\n  windows_memory_physical_free_bytes{job=\"AGENTES\", instance=~\"10.138.3.121|10.138.3.122\"}\r\n  /\r\n  windows_memory_physical_total_bytes{job=\"AGENTES\", instance=~\"10.138.3.121|10.138.3.122\"}\r\n) * 100\r\n\r\n",
     "legendFormat": "Servidores_024Encarnacion"
    }
   ]
  },
  {
   "title": "Detalles de la tarjeta de red",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (instance) (\r\n  irate(windows_net_bytes_sent_total{\r\n    job=\"AGENTES\",\r\n    instance=~\"10.138.3.121|10.138.3.122\",\r\n    nic!~\"isatap.*|VPN.*|Loopback.*|vEthernet.*\"\r\n  }[2m])\r\n) * 8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Servidores_024Encarnacion",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- sum by (instance) (\r\n  irate(windows_net_bytes_received_total{\r\n    job=\"AGENTES\",\r\n    instance=~\"10.138.3.121|10.138.3.122\",\r\n    nic!~\"isatap.*|VPN.*|Loopback.*|vEthernet.*\"\r\n  }[2m])\r\n) * 8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Servidores_024Encarnacion",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "$instance status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "instance" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<h1>Disponibilidad CORE T24 ${instance} </h1> "
   }
  },
  {
   "title": "Estatus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Tiempo promedio de respuesta HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Tiempo total de respuesta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Codigo de Estatus HTTP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version de protocolo HTTP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$instance\"} - time()"
    }
   ]
  },
  {
   "title": "Tiempo medio de respuesta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Tiempo promedio resolución DNS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$instance\"})"
    }
   ]
  }
 ]
}