{
 "title": "IDTC-NOC-DASHGERENCIA-001 - GERENCIA",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Regiones",
    "query": {
     "query": "label_values(windows_os_hostname{job=~\"REGION 1|REGION 3|REGION 2|SRVS_MiCoopeEnLinea|SRVS_VISA|SRV_T24|SRVS_REMESASDIRIGIDAS|SRVS_SOYFRI|SRVS_AGENTES\"},job)"
    }
   },
   {
    "name": "instancia",
    "label": "instancia",
    "query": {
     "query": "label_values(windows_os_hostname{job=\"$job\"},instance)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(windows_os_hostname{job=\"$job\"},hostname)"
    }
   },
   {
    "name": "intervalo",
    "label": "intervalo",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job_servicios",
    "label": "servicios",
    "query": {
     "query": "label_values(probe_success{job=~\"SOY FRI|AGENTES|REMESAS DIRIGIDAS\"},job)"
    }
   },
   {
    "name": "tarjet",
    "label": "tarjet",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   },
   {
    "name": "Check_status",
    "label": "check",
    "query": {
     "query": "label_values(probe_success{job=~\"MiCoopeEnLinea\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uso de CPU DB PRINCIPAL T24",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (\r\n  rate(windows_cpu_time_total{job=\"SRVS_BD\", mode=\"idle\", instance=\"10.138.7.231:9182\"}[10s])\r\n) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STATUS - $job_servicios",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job_servicios\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Uso de CPU SRVS APPL por Job: $job",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (\r\n  rate(windows_cpu_time_total{job=\"$job\", mode=\"idle\"}[10s])\r\n) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU SRVS VISA",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (\r\n  rate(windows_cpu_time_total{job=\"SRVS_VISA\", mode=\"idle\"}[10s])\r\n) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servicio HTTP $Check_status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=\"MiCoopeEnLinea\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}