{
 "title": "ACH",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CODE ACH",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status_code) (\r\n  count_over_time(\r\n    {job=\"ACH_MONITORING\"} \r\n    | regexp `Response Code:\\s*(?P<status_code>\\d{3})`\r\n    | status_code != \"\"\r\n    [$__interval]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Fuerza Bruta",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(status_code) (count_over_time({instance=\"10.138.7.225\", filename=\"LOG_SERVER_JBOSS-EAP-7.2\"} | regexp `Response code\\s*:\\s*(?P<status_code>401|412)` | status_code != `` [$__interval]))"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "__unconfigured-panel",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transacciones rechazadas",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"LOG_SERVER_JBOSS-EAP-7.2\"} \r\n|~ \"payload:\" \r\n|~ \"REJECTED\"\r\n| regexp `\"id\":\\s*(?P<id>\\d+),\\s*\"reference\":\\s*(?P<reference>\\d+)`\r\n| line_format \"payload: {\\\"id\\\": {{.id}}, \\\"reference\\\": {{.reference}}, \\\"status\\\": \\\"REJECTED\\\"}\""
    }
   ]
  }
 ]
}