{
 "title": "SERVICIO SMS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(windows_iis_info{job=~\"SMS\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_iis_info,instance)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(windows_iis_current_application_pool_state{job=~\"$job\", instance=~\"$instance\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running",
   "type": "stat",
   "description": "The current status of the Server",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_iis_current_application_pool_state{app=~\"$app\",state=\"Running\"}"
    }
   ]
  },
  {
   "title": "Current Worker Processes",
   "type": "stat",
   "description": "The current number of worker processes that are running in the application pool",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_iis_current_worker_processes{app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Maximum Worker Processes",
   "type": "stat",
   "description": "The maximum number of worker processes that have been created for the application pool since Windows Process Activation Service (WAS) started",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_iis_maximum_worker_processes{app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "__unconfigured-panel",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests ",
   "type": "bargauge",
   "description": "Number of HTTP requests by type",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(windows_iis_requests_total{site=~\"$app\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Current Application Pool Uptime",
   "type": "library-panel-ref",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<h1 style=\"\r\n    font-size: 3rem;\r\n    font-weight: 700;\r\n    font-family: 'Century';\r\n    color: #49BF22;\r\n    padding-bottom: 7px;\r\n    -- border-bottom: 0.5px solid #FFFFFF;\r\n    text-align: center;\r\n\">\r\n    SERVICIO SMS BD 231\r\n</h1>\r\n"
   }
  },
  {
   "title": "SMS - SERVICIO TOTAL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AnalyticsImport",
     "rawSql": "SELECT \r\n    SUM(row_count) AS Total_Registros\r\nFROM sys.dm_db_partition_stats\r\nWHERE object_id = OBJECT_ID('FBNK_EB_GT01_SMS_SERVICIO')\r\nAND index_id < 2;\r\n"
    }
   ]
  },
  {
   "title": "SMS - No Enviados ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "FENANC",
     "rawSql": "SELECT\r\n\tCOUNT(*) AS 'No Enviados'\r\nFROM FENANC.dbo.FBNK_EB_GT01_SMS_SERVICIO\r\nWHERE XMLRECORD.value('(/row/c24)[1]', 'NVARCHAR(50)') = 'NO.ENVIADO';"
    }
   ]
  },
  {
   "title": "SMS - Enviados ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AnalyticsImport",
     "rawSql": "SELECT\r\n\tCOUNT(*) AS 'No Enviados'\r\nFROM FENANC.dbo.FBNK_EB_GT01_SMS_SERVICIO\r\nWHERE XMLRECORD.value('(/row/c24)[1]', 'NVARCHAR(50)') = 'ENVIADO';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "<h1 style=\"\n    font-size: 3rem;\n    font-weight: 700;\n    font-family: 'Century';\n    color: #49BF22;\n    padding-bottom: 7px;\n    -- border-bottom: 0.5px solid #FFFFFF;\n    text-align: center;\n\">\n    SERVICIO SMS BD 10.138.2.198\n</h1>"
   }
  },
  {
   "title": "Pen",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "AgenteMovilDB",
     "rawSql": "use micoope_sms\r\n\r\nSELECT TOP 20 \r\n\tID,\r\n\tEstatus,\r\n\tDateProcessing AS 'Fecha de Proceso',\r\n\tDescripcionTransaccionDebito AS 'Descripción',\r\n\tCelularDebito AS 'Celular',\r\n\tEstadoEnvioDebito AS 'Estado Debito',\r\n\tEstadoEnvioCredito AS 'Estado Credito',\r\n\tFechaEnvioDebito AS 'Fecha Envio Debito',\r\n\t--FechaEnvioCredito,\r\n\tFechaInsertado AS 'Fecha Insertado',\r\n\tMensajeEstado AS 'Estado'\r\nFROM cnt.smsxenviarft \r\nWHERE MensajeEstado <> 'DEB: Enviado correctamente - ' AND MensajeEstado <> 'CRD: Enviado correctamente - ' AND MensajeEstado <> 'DEB: Enviado correctamente - DEB: Enviado correctamente - '\r\nORDER BY TRY_CONVERT(datetime, DateProcessing, 103) DESC;"
    }
   ]
  },
  {
   "title": "No enviados 'cnt.smsxenviartt'",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "AgenteMovilDB",
     "rawSql": "USE Micoope_SMS\r\n\r\n\r\nSELECT TOP 20\r\n\tID,\r\n\tEstatus,\r\n\tDateProcessing AS 'Fecha de Proceso',\r\n\tDescripcionTransaccionDebito AS 'Descripción',\r\n\tCelularDebito AS 'Celular',\r\n\tEstadoEnvio AS 'Estado',\r\n\tFechaEnvio AS 'Fecha Envio',\r\n\tFechaInsertado AS 'Fecha Insertado',\r\n\tMensajeEstado AS 'Mensaje' \r\nFROM cnt.smsxenviartt\r\nWHERE MensajeEstado <> 'Enviado correctamente'\r\nORDER BY TRY_CONVERT(datetime, DateProcessing, 103) DESC;"
    }
   ]
  },
  {
   "title": "Cola de Mensajes",
   "type": "bargauge",
   "description": "Resumen de mensajes encolados por Tipo",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "Use Micoope_SMS\r\n\r\nSELECT\r\n    'FT_CREDITO' AS Tipo,\r\n    COUNT(*) AS Pendientes\r\nFROM cnt.smsxenviarft\r\nWHERE EstadoEnvioCredito = 'P'\r\nAND FechaInsertado >= CAST(GETDATE() AS DATE)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'FT_DEBITO',\r\n    COUNT(*)\r\nFROM cnt.smsxenviarft\r\nWHERE EstadoEnvioDebito = 'P'\r\nAND FechaInsertado >= CAST(GETDATE() AS DATE)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'TT',\r\n    COUNT(*)\r\nFROM cnt.smsxenviartt\r\nWHERE EstadoEnvio = 'P'\r\nAND FechaInsertado >= CAST(GETDATE() AS DATE)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'AA',\r\n    COUNT(*)\r\nFROM cnt.smsxenviaraa\r\nWHERE EstadoEnvio = 'P'\r\nAND FechaInsertado >= CAST(GETDATE() AS DATE);\r\n"
    }
   ]
  },
  {
   "title": "Tiempo de Cola SMS",
   "type": "gauge",
   "description": "Tiempo estimado de encolamiento de mensajes",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "USE Micoope_SMS;\r\n\r\nWITH Datos AS (\r\n    SELECT ISNULL(MAX(DATEDIFF(SECOND, FechaInsertado, GETDATE())), 0) AS SegundosTotales\r\n    FROM (\r\n        SELECT FechaInsertado\r\n        FROM cnt.smsxenviarft\r\n        WHERE EstadoEnvioCredito = 'P'\r\n\r\n        UNION ALL\r\n\r\n        SELECT FechaInsertado\r\n        FROM cnt.smsxenviarft\r\n        WHERE EstadoEnvioDebito = 'P'\r\n\r\n        UNION ALL\r\n\r\n        SELECT FechaInsertado\r\n        FROM cnt.smsxenviartt\r\n        WHERE EstadoEnvio = 'P'\r\n\r\n        UNION ALL\r\n\r\n        SELECT FechaInsertado\r\n        FROM cnt.smsxenviaraa\r\n        WHERE EstadoEnvio = 'P'\r\n    ) A\r\n)\r\nSELECT\r\n    --SegundosTotales,\r\n    SegundosTotales / 86400 AS Dias,\r\n    (SegundosTotales % 86400) / 3600 AS Horas,\r\n    (SegundosTotales % 3600) / 60 AS Minutos,\r\n    SegundosTotales % 60 AS Segundos,\r\n    CONCAT(\r\n        SegundosTotales / 86400, 'd ',\r\n        (SegundosTotales % 86400) / 3600, 'h ',\r\n        (SegundosTotales % 3600) / 60, 'm ',\r\n        SegundosTotales % 60, 's'\r\n    ) AS TiempoMasAntiguo\r\nFROM Datos;"
    }
   ]
  },
  {
   "title": "Tendencia de Cola",
   "type": "timeseries",
   "description": "Permite saber si el backlog está aumentando.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "dataset": "master",
     "rawSql": "USE Micoope_SMS;\r\n\r\n;WITH Minutos AS (\r\n    SELECT DATEADD(MINUTE,-360,DATEADD(MINUTE,DATEDIFF(MINUTE,0,GETDATE()),0)) AS [time]\r\n    UNION ALL\r\n    SELECT DATEADD(MINUTE,1,[time])\r\n    FROM Minutos\r\n    WHERE [time] < DATEADD(MINUTE,DATEDIFF(MINUTE,0,GETDATE()),0)\r\n)\r\nSELECT\r\n    m.[time],\r\n    ISNULL(x.Pendientes,0) AS Pendientes\r\nFROM Minutos m\r\nLEFT JOIN (\r\n    SELECT\r\n        DATEADD(MINUTE,DATEDIFF(MINUTE,0,FechaInsertado),0) AS [time],\r\n        COUNT(*) AS Pendientes\r\n    FROM cnt.smsxenviartt\r\n    WHERE EstadoEnvio = 'P'\r\n      AND $__timeFilter(FechaInsertado)\r\n    GROUP BY DATEADD(MINUTE,DATEDIFF(MINUTE,0,FechaInsertado),0)\r\n) x\r\n    ON m.[time] = x.[time]\r\nORDER BY m.[time]\r\nOPTION (MAXRECURSION 400);"
    }
   ]
  }
 ]
}