{
 "title": "Monitoreo_Sintetico_T24_Appl",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(k6_checks_rate, region)"
    }
   },
   {
    "name": "segmento",
    "label": "segmento",
    "query": {
     "query": "label_values(k6_checks_rate{region=~\"$region\"}, segmento)"
    }
   },
   {
    "name": "instancia",
    "label": "instancia",
    "query": {
     "query": "label_values(k6_checks_rate{segmento=~\"$segmento\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disponibilidad Global",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(k6_checks_rate) * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P99 Latencia Login",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(k6_http_req_duration_p99)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tasa de Errores",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(k6_http_req_failed_rate)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Comparativa de Sub-regiones",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_p99) by (segmento)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errores por Código de Estado HTTP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{region=~\"$region\", segmento=~\"$segmento\", instance=~\"$instancia\"}) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "avg(k6_http_req_connecting_p99)",
     "legendFormat": "RED"
    },
    { "expr": "avg(k6_http_req_waiting_p99)", "legendFormat": "APP" }
   ]
  },
  {
   "title": "Status History",
   "type": "status-history",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "k6_checks_rate{check=\"T24 Responsive\", job=\"SRVS_APPL_T24\", region=~\"$region\", segmento=~\"$segmento\", instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}:{{port}}"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99{step=\"authentication_check\", method=\"POST\", region=~\"$region\", segmento=~\"$segmento\", instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}:{{port}}"
    }
   ]
  }
 ]
}