{
 "title": "Reportes_nocturnos",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(windows_physical_disk_reads_total{job=~\"BD|SRVS_APPL_T24\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({instance=~\"10.138.29.125:9182|10.138.7.231\"},instance)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Consultas VISA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 2000,
     "metricsQueryType": "range",
     "query": "{resource.client=\"VISA\" && duration > 6s} >> {name =~ \"SELECT.*\" && duration > 800ms}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "USO DE CPU DEL JOB【$job】",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(windows_cpu_time_total{job=\"$job\", mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=\"$job\", mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "Promedio total"
    }
   ]
  },
  {
   "title": "Errores 404",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_method, http_route, http_status_code, host_name) (increase(http_server_duration_milliseconds_count{host_ip=\"10.138.29.125\", http_status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ATM Queue Publish all servers Rechazos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "filters": [
      {
       "id": "9a91662f",
       "operator": "=~",
       "scope": "resource",
       "tag": "host.name",
       "value": [
        "DSSIMWS01",
        "DSSIMWS08",
        "DSSIMWS09"
       ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "ATMReplyQueue publish" ],
       "valueType": "string"
      },
      {
       "id": "5a45d1fd",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": []
      },
      {
       "id": "7a43e9e5",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "name",
       "value": []
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "7s",
       "valueType": "duration"
      },
      { "id": "duration-type", "value": "trace" }
     ],
     "limit": 100000,
     "metricsQueryType": "range",
     "query": "{resource.host.name=~\"DSSIMWS01|DSSIMWS08|DSSIMWS09\" && name=\"ATMReplyQueue publish\" && traceDuration>7s}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Uso de CPU BD PROD T24", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 } },
  { "title": "ATM Queue Publish all servers", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 } },
  {
   "title": "Uso de CPU SRVS VISA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(windows_cpu_time_total{instance=~\"10.138.7.219:9182|10.138.7.218:9182|10.138.7.232:9182\", mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}