{
 "title": "SERVICIOS TSM T24",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "status", "label": "status", "query": "UP, DOWN" }
  ]
 },
 "panels": [
  {
   "title": "Servicios caidos ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "services_down{instance=\"127.0.0.1:9200\"}",
     "legendFormat": "{{services_down}}"
    }
   ]
  },
  {
   "title": "Customer.api",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "service_status{service_name=~\"GT.*.CUSTOMER.API.UPDATE\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "TSM Conteo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(service_status{service_name=\"TSM\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carga.Masiva Conteo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(service_status{service_name=~\"A.*/FT.CARGA.MASIVA\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulation. Conteo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(service_status{service_name=~\"A.*/AA.SIMULATION.SERVICE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SERVICIO SMS STATUS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(service_status{service_name=\"BNK/GT01.SEND.SERV.FT.TT\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SERVICIO ACH STATUS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(service_status{service_name=\"BNK/GT01.PROCESS.ACH.INWARD\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TSM PM Caidos",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shift_service_status==0", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "BNK",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "service_status{service_name=~\"BNK/AA.SIMULATION.SERVICE|BNK/GT01.SEND.SERV.FT.TT|BNK/OFS.MESSAGE.SERVICE|BNK/REVIEW.STATUS.AND.SESSION\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "TSM",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_status{service_name=\"TSM\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Carga.Masiva",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "service_status{service_name=~\"A.*/FT.CARGA.MASIVA\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Simulation.Service",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "service_status{service_name=~\"A.*/AA.SIMULATION.SERVICE|BNK/AA.SIMULATION.SERVICE\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}